### Example 1.a - Using a 1-D Array of Integers (Rank #1 Array)


In [62]:
import numpy as np

# We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])

# Let's print the ndarray we just created using the print() command
print('x = ', x)

x =  [1 2 3 4 5]


In [63]:
# We print information about x
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
print('x has dimensions:', x.shape)
print('x has size:', x.size)

x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64
x has dimensions: (5,)
x has size: 5


### Example 1.b  - Using 1-D Array of Strings (Rank #1 Array)

In [64]:
# We create a rank 1 ndarray that only contains strings
x = np.array(['Hello', 'World'])

# We print information about x
print('x = ', x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['Hello' 'World']
x has dimensions: (2,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U5


### Example 1.c - Using a 1-D Array of Int and String (Rank #1 Array)
***NumPy will assign each element a same datatype because NumPy arrays must contains elements of same type.***

In [65]:
# We create a rank 1 ndarray from a Python list that contains integers and strings
x = np.array([1, 2, 'World'])

# We print information about x
print('x = ', x)
print('x has dimensions:', x.shape) 
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['1' '2' 'World']
x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U21


### Example 1.d - Using a 1-D Array of Int and Float
***Upcasting demo*** - All integers will be converted (upgraded) to Float datatype. It is called upcasting, not downcasting, because a Float has a precision value (digits after the decimal). 

In [66]:
# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int64
The elements in y are of type: float64
The elements in z are of type: float64


### Example 1.e - Using a 1-D Array of Float, and specifying the datatype of each element as int64
***NOTE*** - Precision will be lost in this example

In [67]:
# We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

# We print the dtype x
print('x = ', x)
print('The elements in x are of type:', x.dtype)

x =  [1 2 3 4 5]
The elements in x are of type: int64


### Example 2 - Using a 2-D Array (Rank #2 Array)

In [68]:
# We create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

# We print information about Y
print('Y = \n', Y)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')

Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64
Y has dimensions: (4, 3)
Y has a total of 12 elements


### Example 3 - Save the NumPy array to a File


In [69]:
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

# We save x into the current directory as 
np.save('my_array', x)

In [70]:
# We load the saved array from our current directory into variable y
y = np.load('my_array.npy')

# We print information about the ndarray we loaded
print('Y = \n', y)
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)

Y = 
 [1 2 3 4 5]
y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int64


### Using Built-in Functions to Create ndarrays

In [71]:
my_list = [1, 2, 3, 4, 5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [72]:
x = np.zeros((3, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [73]:
print(x.dtype)

float64


In [74]:
x = np. ones((3, 4),dtype=int)
print(x)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [75]:
x = np.full((3, 4), 5)
print(x)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [76]:
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [77]:
x = np.diag([10,20,30,40,50])
print(x)

[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


In [78]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [79]:
x = np.arange(4,10)
print(x)

[4 5 6 7 8 9]


In [80]:
x = np.arange(0,10,2)
print(x)

[0 2 4 6 8]


In [81]:
x = np.linspace(0, 25, 10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [82]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [83]:
x = np.reshape(x, (5,4))
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [84]:
x = np.random.random((3,4))
print(x)

[[0.60894918 0.49575549 0.06654424 0.47314885]
 [0.7315512  0.39353441 0.87039805 0.79488046]
 [0.86276476 0.48906387 0.55434255 0.29594463]]


In [85]:
x = np.random.randint(4,15, (3,2))
print(x)

[[ 6 13]
 [12 10]
 [11  7]]


In [86]:
x = np.random.normal(0,0.1, size=(1000,1000))
print(x)

[[-0.03137399  0.0580417   0.19176851 ... -0.01538492  0.01691719
   0.06942318]
 [ 0.03961462  0.13666066 -0.05860969 ...  0.01853884  0.06164319
   0.03737698]
 [-0.03496008  0.03452112 -0.09823027 ... -0.13927632  0.1764223
   0.01861795]
 ...
 [ 0.01038363 -0.11016359 -0.03772714 ...  0.01254111  0.07228548
  -0.00411932]
 [ 0.04466694 -0.15012346  0.04049558 ... -0.07595279  0.07850869
  -0.05619974]
 [ 0.04293592 -0.15440655  0.118456   ...  0.01694103  0.05710023
  -0.06922281]]
