### Example 1.a - Using a 1-D Array of Integers (Rank #1 Array)


In [14]:
import numpy as np

# We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])

# Let's print the ndarray we just created using the print() command
print('x = ', x)

x =  [1 2 3 4 5]


In [16]:
# We print information about x
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
print('x has dimensions:', x.shape)
print('x has size:', x.size)

x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64
x has dimensions: (5,)
x has size: 5


### Example 1.b  - Using 1-D Array of Strings (Rank #1 Array)

In [18]:
# We create a rank 1 ndarray that only contains strings
x = np.array(['Hello', 'World'])

# We print information about x
print('x = ', x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['Hello' 'World']
x has dimensions: (2,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U5


### Example 1.c - Using a 1-D Array of Int and String (Rank #1 Array)
***NumPy will assign each element a same datatype because NumPy arrays must contains elements of same type.***

In [19]:
# We create a rank 1 ndarray from a Python list that contains integers and strings
x = np.array([1, 2, 'World'])

# We print information about x
print('x = ', x)
print('x has dimensions:', x.shape) 
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['1' '2' 'World']
x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U21


### Example 1.d - Using a 1-D Array of Int and Float
***Upcasting demo*** - All integers will be converted (upgraded) to Float datatype. It is called upcasting, not downcasting, because a Float has a precision value (digits after the decimal). 

In [20]:
# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int64
The elements in y are of type: float64
The elements in z are of type: float64


### Example 1.e - Using a 1-D Array of Float, and specifying the datatype of each element as int64
***NOTE*** - Precision will be lost in this example

In [21]:
# We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

# We print the dtype x
print('x = ', x)
print('The elements in x are of type:', x.dtype)

x =  [1 2 3 4 5]
The elements in x are of type: int64


### Example 2 - Using a 2-D Array (Rank #2 Array)

In [22]:
# We create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

# We print information about Y
print('Y = \n', Y)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')

Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64
Y has dimensions: (4, 3)
Y has a total of 12 elements


### Example 3 - Save the NumPy array to a File


In [23]:
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

# We save x into the current directory as 
np.save('my_array', x)

In [24]:
# We load the saved array from our current directory into variable y
y = np.load('my_array.npy')

# We print information about the ndarray we loaded
print('Y = \n', y)
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)

Y = 
 [1 2 3 4 5]
y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int64


### Using Built-in Functions to Create ndarrays

In [26]:
my_list = [1, 2, 3, 4, 5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [31]:
x = np.zeros((3, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [32]:
print(x.dtype)

float64


In [36]:
x = np. ones((3, 4),dtype=int)
print(x)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [37]:
x = np.full((3, 4), 5)
print(x)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [38]:
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [40]:
x = np.diag([10,20,30,40,50])
print(x)

[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


In [42]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [44]:
x = np.arange(4,10)
print(x)

[4 5 6 7 8 9]


In [45]:
x = np.arange(0,10,2)
print(x)

[0 2 4 6 8]


In [46]:
x = np.linspace(0, 25, 10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [47]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [52]:
x = np.reshape(x, (5,4))
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [55]:
x = np.random.random((3,4))
print(x)

[[0.9789608  0.85777052 0.14555084 0.07796299]
 [0.46992693 0.8335448  0.67818104 0.87713902]
 [0.38858604 0.95657503 0.93678563 0.90297338]]


In [59]:
x = np.random.randint(4,15, (3,2))
print(x)

[[12 12]
 [11  5]
 [ 5  5]]


In [60]:
x = np.random.normal(0,0.1, size=(1000,1000))
print(x)

[[-0.08907596 -0.0913093  -0.00075553 ... -0.13612053  0.08068494
  -0.13548741]
 [ 0.01604621  0.00443627  0.07972541 ... -0.03133691 -0.01149279
   0.07275644]
 [-0.02844099  0.01487612  0.08614622 ... -0.10264601  0.08712597
  -0.01277525]
 ...
 [ 0.09583006 -0.17598542  0.0354086  ... -0.07210743  0.13029154
   0.02289041]
 [-0.09635898  0.0682065  -0.13420592 ... -0.08009989 -0.02730162
   0.02845223]
 [-0.0661271   0.03777904  0.0986398  ... -0.08781953 -0.033032
  -0.058915  ]]
